version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: makerschedule_postgres
    environment:
      POSTGRES_DB: makerschedule
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d makerschedule"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - makerschedule-network

  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: makerschedule_api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: dotnet MakerSchedule.API.dll --urls "http://0.0.0.0:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=makerschedule;Username=appuser;Password=${DB_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - UseAzureKeyVault=false
      - UseAzureStorage=false
    restart: unless-stopped
    networks:
      - makerschedule-network

volumes:
  postgres_data:

networks:
  makerschedule-network:
    driver: bridge
