// <auto-generated />
using System;
using MakerSchedule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakerSchedule.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250829174937_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DomainUsers");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassSize")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventTagIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ClassSize = 1,
                            Description = "Advanced pottery techniques for experienced artists. Wheel throwing and glazing. In this workshop, participants will explore complex forms and surface decoration methods, including carving, slip trailing, and underglaze painting. The instructor will demonstrate advanced wheel techniques, such as making large vessels and assembling multi-part pieces. You will also learn about glaze chemistry, firing schedules, and troubleshooting common issues. Bring your creative ideas and prepare to push your skills to the next level. All materials and firing fees are included. Prior pottery experience is required for this class.",
                            Duration = 120,
                            EventName = "Advanced Pottery",
                            EventTagIds = "[]",
                            Price = 71.1953666684232m
                        },
                        new
                        {
                            Id = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ClassSize = 0,
                            Description = "Learn to build a simple wooden shelf. All materials provided. This hands-on workshop covers the basics of woodworking, including measuring, cutting, sanding, and assembling wood pieces. You will use both hand and power tools under the guidance of an experienced instructor. Safety procedures and tool maintenance will be emphasized throughout the session. By the end of the class, you will have constructed your own sturdy shelf to take home. The workshop also includes tips on finishing techniques, such as staining and sealing, to enhance the appearance and durability of your project. Suitable for all skill levels.",
                            Duration = 180,
                            EventName = "Woodworking Workshop",
                            EventTagIds = "[]",
                            Price = 109.96078555497m
                        },
                        new
                        {
                            Id = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ClassSize = 0,
                            Description = "Introduction to sewing for beginners. Learn to use a sewing machine and create simple projects. This class covers the fundamentals of sewing, including threading a machine, selecting fabrics, reading patterns, and basic stitches. You will practice on scrap fabric before creating a simple project to take home. The instructor will provide guidance on choosing the right materials and tools for your projects. Perfect for those who want to start sewing their own clothes or home decor items. All equipment and materials are provided.",
                            Duration = 90,
                            EventName = "Sewing Basics",
                            EventTagIds = "[]",
                            Price = 78.9516634294634m
                        });
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduleStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Occurrences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a335874-0df4-474d-82bf-0da2503975ec"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 8, 22, 15, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("11fb3d9d-d1bd-4df7-b322-6d7facf63cee"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 9, 10, 20, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ef414ee9-fe83-46cc-b8f1-5b0f0bb5086a"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 7, 25, 16, 15, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("102a0163-ed44-4d83-8619-43254df61540"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 9, 13, 17, 15, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("3f08556a-4241-49a2-bb50-5e08f5040a91"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 8, 27, 21, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0694e0cb-4531-4072-8415-f82e2400e3b8"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 9, 5, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("b5f95449-7628-4f2d-91ff-6d2652112a91"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 8, 27, 20, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("25a34489-fe74-4a62-9501-4bf8e62c7094"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 9, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("369ae79d-11e5-4ec3-8e47-d2ee6f34d860"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 8, 15, 19, 45, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("7c31865b-2951-4fa9-9108-eec3cf96b6c0"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 9, 23, 21, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("bd19cf28-2808-4fcc-8f9a-7ced8f21806c"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 8, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("4f5470fc-84ee-4ef4-b1df-6a9cc4de3082"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 8, 23, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("6d06bb09-b6f7-43fd-a276-64027befe7e2"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 9, 28, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("e277afac-015b-4581-b5b5-5ba4931a69a5"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 8, 5, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("1b568239-8fac-46fc-91a0-23acc580f58a"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 9, 27, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("e5dc26f4-0cba-485b-b9b9-c07fefdac0ed"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 8, 16, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("bbb98f62-fd20-4e8b-b3f7-5033ba3aae7d"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 9, 19, 14, 45, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("UserId");

                    b.ToTable("OccurrenceAttendees");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceLeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("UserId");

                    b.ToTable("OccurrenceLeaders");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MakerSchedule.Domain.Entities.EventTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", "User")
                        .WithOne("DomainUser")
                        .HasForeignKey("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Occurrence", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.Event.Event", "Event")
                        .WithMany("Occurrences")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceAttendee", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.Event.Occurrence", "Occurrence")
                        .WithMany("Attendees")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", "User")
                        .WithMany("OccurrencesAttended")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceLeader", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.Event.Occurrence", "Occurrence")
                        .WithMany("Leaders")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", "User")
                        .WithMany("OccurrencesLed")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", b =>
                {
                    b.Navigation("OccurrencesAttended");

                    b.Navigation("OccurrencesLed");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Event", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Occurrence", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Leaders");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.User.User", b =>
                {
                    b.Navigation("DomainUser");
                });
#pragma warning restore 612, 618
        }
    }
}
