// <auto-generated />
using System;
using MakerSchedule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakerSchedule.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250818053255_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventEventTag", b =>
                {
                    b.Property<Guid>("EventTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventTagsId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("EventEventTag");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DomainUsers");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            Description = "Advanced pottery techniques for experienced artists. Wheel throwing and glazing. In this workshop, participants will explore complex forms and surface decoration methods, including carving, slip trailing, and underglaze painting. The instructor will demonstrate advanced wheel techniques, such as making large vessels and assembling multi-part pieces. You will also learn about glaze chemistry, firing schedules, and troubleshooting common issues. Bring your creative ideas and prepare to push your skills to the next level. All materials and firing fees are included. Prior pottery experience is required for this class.",
                            Duration = 120,
                            EventName = "Advanced Pottery"
                        },
                        new
                        {
                            Id = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            Description = "Learn to build a simple wooden shelf. All materials provided. This hands-on workshop covers the basics of woodworking, including measuring, cutting, sanding, and assembling wood pieces. You will use both hand and power tools under the guidance of an experienced instructor. Safety procedures and tool maintenance will be emphasized throughout the session. By the end of the class, you will have constructed your own sturdy shelf to take home. The workshop also includes tips on finishing techniques, such as staining and sealing, to enhance the appearance and durability of your project. Suitable for all skill levels.",
                            Duration = 180,
                            EventName = "Woodworking Workshop"
                        },
                        new
                        {
                            Id = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            Description = "Introduction to sewing for beginners. Learn to use a sewing machine and create simple projects. This class covers the fundamentals of sewing, including threading a machine, selecting fabrics, reading patterns, and basic stitches. You will practice on scrap fabric before creating a simple project to take home. The instructor will provide guidance on choosing the right materials and tools for your projects. Perfect for those who want to start sewing their own clothes or home decor items. All equipment and materials are provided.",
                            Duration = 90,
                            EventName = "Sewing Basics"
                        });
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduleStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Occurrences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05a33db3-dca0-40e4-ab35-3924e3eaf679"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 8, 11, 15, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8cb4ffaf-dabc-4129-a82d-d1c4024041ce"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 8, 30, 20, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("77e8214f-3535-4cc5-882d-d1e816b1c7dc"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 7, 14, 16, 15, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8096a167-f971-422b-8e0b-3fa20dfb97c7"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 9, 2, 17, 15, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("02fa7df6-bf02-4b53-9e56-940c1937231f"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 8, 16, 21, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("cd6fee30-02eb-4c30-bc45-622ce7ac813a"),
                            EventId = new Guid("c2f8d0f9-b2af-4d3a-91da-13c112c6212c"),
                            ScheduleStart = new DateTime(2025, 8, 25, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8589426f-eccf-4192-a8a9-de88c7824d71"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 8, 16, 20, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("b8e5c515-1443-431f-bcaf-680a4a9eab9a"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 9, 19, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("6b6caca3-15c9-4aee-bea8-305cf1402e77"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 8, 4, 19, 45, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("18b99252-9b25-4518-a0b7-f6d557a41338"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 9, 12, 21, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8f7131fc-e226-413c-815f-a524e570bbf8"),
                            EventId = new Guid("3709300b-3c35-4350-9f3c-277759214bbb"),
                            ScheduleStart = new DateTime(2025, 8, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ebf1a586-9683-477d-95da-05a964bd7b28"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 8, 12, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("481d89a6-6eca-4711-a160-444ae5aa05d6"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 9, 17, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("659e6c70-79c7-4930-b5f5-5403cb6b4d09"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 7, 25, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("45e5c36a-c3b9-4dbd-b532-9bb81d6c54e1"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 9, 16, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("8352a415-8b56-4a81-863c-b6183fa99a23"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 8, 5, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0845ac04-3fe6-4563-a05f-c2cc1a79ba62"),
                            EventId = new Guid("5df8ac2c-b1af-4f9d-861d-a3e1e42b23ec"),
                            ScheduleStart = new DateTime(2025, 9, 8, 14, 45, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("UserId");

                    b.ToTable("OccurrenceAttendees");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceLeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("UserId");

                    b.ToTable("OccurrenceLeaders");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MakerSchedule.Domain.Entities.EventTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EventEventTag", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Entities.EventTag", null)
                        .WithMany()
                        .HasForeignKey("EventTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerSchedule.Domain.Aggregates.Event.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", "User")
                        .WithOne("DomainUser")
                        .HasForeignKey("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Occurrence", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.Event.Event", "Event")
                        .WithMany("Occurrences")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceAttendee", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.Event.Occurrence", "Occurrence")
                        .WithMany("Attendees")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", "User")
                        .WithMany("OccurrencesAttended")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.OccurrenceLeader", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.Event.Occurrence", "Occurrence")
                        .WithMany("Leaders")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", "User")
                        .WithMany("OccurrencesLed")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MakerSchedule.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.DomainUser.DomainUser", b =>
                {
                    b.Navigation("OccurrencesAttended");

                    b.Navigation("OccurrencesLed");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Event", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.Event.Occurrence", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Leaders");
                });

            modelBuilder.Entity("MakerSchedule.Domain.Aggregates.User.User", b =>
                {
                    b.Navigation("DomainUser");
                });
#pragma warning restore 612, 618
        }
    }
}
