name: Build and deploy .NET backend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - "MakeScheduleBE/**"
      - ".github/workflows/azure-deploy.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore MakeScheduleBE/MakerSchedule.API/MakerSchedule.API.csproj

      - name: Build
        run: dotnet build MakeScheduleBE/MakerSchedule.API/MakerSchedule.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish MakeScheduleBE/MakerSchedule.API/MakerSchedule.API.csproj --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
