name: Database Migrations

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
    paths:
      - "MakeScheduleBE/MakerSchedule.Infrastructure/Migrations/**"
      - ".github/workflows/database-migrations.yml"
  pull_request:
    branches:
      - main
    paths:
      - "MakeScheduleBE/MakerSchedule.Infrastructure/Migrations/**"
      - ".github/workflows/database-migrations.yml"

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Apply Database Migrations
        run: |
          cd MakeScheduleBE/MakerSchedule.API
          dotnet tool install --global dotnet-ef
          export ASPNETCORE_ENVIRONMENT="Production"
          export ConnectionStrings__DefaultConnection="Server=tcp:makerschedule.database.windows.net,1433;Initial Catalog=makerschedule-db;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;User ID=${{ secrets.DB_USERNAME }};Password=${{ secrets.DB_PASSWORD }};"
          echo "Waiting for Azure SQL to wake up..."
          sleep 180
          dotnet ef database update --verbose

      - name: Verify Migration Status
        run: |
          cd MakeScheduleBE/MakerSchedule.API
          dotnet ef migrations list
